### ISSUE TITLE
TODO: Implement PlayerBottomSheet Functionality

### ISSUE THREAD

**Issue by joh9911** [joh9911/Transpose#1]
- [x] Implement PlayerBottomSheet using nested Scaffold
- [x] Interaction between PlayerBottomSheet and existing Composable
- [x] Resizable Composable according to drag state
- [x] Alpha value change according to drag state
- [x] #10
