### ISSUE TITLE
TODO: Implement MediaSession Service

### ISSUE THREAD

**Issue by joh9911** [joh9911/Transpose#2]
- [x] Implement MediaSession Service
- [x] Modularize MediaSession Component (DI, Repository, ViewModel)
- [x] Implement AudioEffect methods interacted between Service and Component
- [x] Interact with MediaController through ViewModel
