### ISSUE TITLE
TODO: Modularize NavComponent

### ISSUE THREAD

**Issue by joh9911** [joh9911/Transpose#3]
- [x] Create Navigation ViewModel
- [x] divide HiltViewModel() and ViewModel()
- [x] organize in directory
