### ISSUE TITLE
TODO: Implement ConvertMainPage

### ISSUE THREAD

**Issue by joh9911** [joh9911/Transpose#4]
- [x] Create ConvertNavComponent
- [x] Implement AudioEdit Page
- [x] Complete AudioEdit Methods
- [x] Implement SearchResult Page
