### ISSUE TITLE
TODO: Complete App

### ISSUE THREAD

**Issue by joh9911** [joh9911/Transpose#8]
- [x] scroll up when clicking the related items
- [x] #11
- [ ] add channel page
- [x] add feature of creating my playlists
- [x] add localItem play logic
- [ ] create logic of playing the playlist type item through related items
- [x] play playlist type item though Search Page
- [ ] change nested Navhost to single structure
